apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hf-provisioner-ec2
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hf-provisioner-ec2
rules:
  - apiGroups: ['provisioning.hobbyfarm.io']
    resources: ['instances', 'keypairs', 'instances/status', 'keypairs/status']
    verbs: ['*']
  - apiGroups: ['hobbyfarm.io']
    resources: ['virtualmachines', 'environments', 'virtualmachinetemplates', 'virtualmachines/status']
    verbs: ['*']
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hf-provisioner-ec2
subjects:
  - kind: ServiceAccount
    name: {{ include "hf-provisioner-ec2.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: hf-provisioner-ec2
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hf-provisioner-ec2
subjects:
  - kind: ServiceAccount
    name: {{ include "hf-provisioner-ec2.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: hf-provisioner-ec2
  apiGroup: rbac.authorization.k8s.io
